[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
dependsOn = ["setup"]
cmds = ["cd backend && npm install"]

[phases.build]
dependsOn = ["install"]
cmds = ["cd backend && npm run build || true"]

[start]
cmd = "cd backend && npm start"